version: "3.9"
services:
  db:
    image: postgres:13
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: UserDB
    ports:
      - "5435:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
volumes:
  postgres_data: